//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public string nombre { get; set; }
        public string apellido { get; set; }
        public long dni { get; set; }
        public string domicilio { get; set; }
        public long telefono { get; set; }
        public string email { get; set; }
        public string estado { get; set; }
    }
}
